INSERT INTO categories (id, label) VALUES
  ('arts', 'Arts'),
  ('food', 'Food'),
  ('general', 'General'),
  ('geography', 'Geography'),
  ('language', 'Language'),
  ('math', 'Math'),
  ('nature', 'Nature'),
  ('science', 'Science'),
  ('sports', 'Sports');

INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('continents', 'How many continents are there?', 'geography', 1, 1),
  ('closest-planet', 'Which planet is closest to the Sun?', 'science', 1, 1),
  ('paris', 'What is the capital of France?', 'geography', 1, 1),
  ('hexagon', 'How many sides does a hexagon have?', 'math', 1, 1),
  ('pacific', 'Which ocean is the largest?', 'geography', 1, 1),
  ('nectar', 'What do bees collect from flowers to make honey?', 'nature', 1, 1),
  ('hour', 'How many minutes are in an hour?', 'math', 1, 1),
  ('co2', 'Which gas do plants take in from the air?', 'science', 1, 1),
  ('water', 'What is H2O better known as?', 'science', 1, 1),
  ('piano', 'Which instrument has 88 keys on a standard model?', 'arts', 1, 1),
  ('soccer', 'How many players does a soccer team have on the field?', 'sports', 1, 1),
  ('diamond', 'What is the hardest natural substance?', 'science', 1, 1),
  ('italy', 'Which country is shaped like a boot?', 'geography', 1, 1),
  ('freeze', 'What is the freezing point of water in Celsius?', 'science', 1, 1),
  ('kangaroo', 'Which animal is a marsupial?', 'nature', 1, 1),
  ('alphabet', 'How many letters are in the English alphabet?', 'language', 1, 1),
  ('guacamole', 'What is the main ingredient in guacamole?', 'food', 1, 1),
  ('mercury-metal', 'Which metal is liquid at room temperature?', 'science', 1, 1),
  ('leap-year', 'How many days are in a leap year?', 'math', 1, 1),
  ('ruby', 'What color is a ruby?', 'general', 1, 1),
  ('elephant', 'Which is the largest land animal?', 'nature', 1, 1),
  ('puppy', 'What do you call a baby dog?', 'nature', 1, 1),
  ('sunrise', 'Which direction does the sun rise?', 'science', 1, 1),
  ('thousand', 'How many zeros are in one thousand?', 'math', 1, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('continents', 0, '5', 0),
  ('continents', 1, '6', 0),
  ('continents', 2, '7', 1),
  ('continents', 3, '8', 0),
  ('closest-planet', 0, 'Venus', 0),
  ('closest-planet', 1, 'Mercury', 1),
  ('closest-planet', 2, 'Mars', 0),
  ('closest-planet', 3, 'Earth', 0),
  ('paris', 0, 'Lyon', 0),
  ('paris', 1, 'Marseille', 0),
  ('paris', 2, 'Nice', 0),
  ('paris', 3, 'Paris', 1),
  ('hexagon', 0, '5', 0),
  ('hexagon', 1, '6', 1),
  ('hexagon', 2, '7', 0),
  ('hexagon', 3, '8', 0),
  ('pacific', 0, 'Atlantic', 0),
  ('pacific', 1, 'Indian', 0),
  ('pacific', 2, 'Arctic', 0),
  ('pacific', 3, 'Pacific', 1),
  ('nectar', 0, 'Pollen', 0),
  ('nectar', 1, 'Nectar', 1),
  ('nectar', 2, 'Sap', 0),
  ('nectar', 3, 'Dew', 0),
  ('hour', 0, '30', 0),
  ('hour', 1, '60', 1),
  ('hour', 2, '90', 0),
  ('hour', 3, '100', 0),
  ('co2', 0, 'Oxygen', 0),
  ('co2', 1, 'Nitrogen', 0),
  ('co2', 2, 'Carbon dioxide', 1),
  ('co2', 3, 'Hydrogen', 0),
  ('water', 0, 'Salt', 0),
  ('water', 1, 'Water', 1),
  ('water', 2, 'Oxygen', 0),
  ('water', 3, 'Hydrogen peroxide', 0),
  ('piano', 0, 'Violin', 0),
  ('piano', 1, 'Guitar', 0),
  ('piano', 2, 'Piano', 1),
  ('piano', 3, 'Harp', 0),
  ('soccer', 0, '9', 0),
  ('soccer', 1, '10', 0),
  ('soccer', 2, '11', 1),
  ('soccer', 3, '12', 0),
  ('diamond', 0, 'Gold', 0),
  ('diamond', 1, 'Iron', 0),
  ('diamond', 2, 'Quartz', 0),
  ('diamond', 3, 'Diamond', 1),
  ('italy', 0, 'Spain', 0),
  ('italy', 1, 'Italy', 1),
  ('italy', 2, 'Greece', 0),
  ('italy', 3, 'Portugal', 0),
  ('freeze', 0, '0', 1),
  ('freeze', 1, '32', 0),
  ('freeze', 2, '100', 0),
  ('freeze', 3, '-10', 0),
  ('kangaroo', 0, 'Dolphin', 0),
  ('kangaroo', 1, 'Penguin', 0),
  ('kangaroo', 2, 'Kangaroo', 1),
  ('kangaroo', 3, 'Crocodile', 0),
  ('alphabet', 0, '24', 0),
  ('alphabet', 1, '25', 0),
  ('alphabet', 2, '26', 1),
  ('alphabet', 3, '27', 0),
  ('guacamole', 0, 'Tomato', 0),
  ('guacamole', 1, 'Pepper', 0),
  ('guacamole', 2, 'Onion', 0),
  ('guacamole', 3, 'Avocado', 1),
  ('mercury-metal', 0, 'Iron', 0),
  ('mercury-metal', 1, 'Mercury', 1),
  ('mercury-metal', 2, 'Silver', 0),
  ('mercury-metal', 3, 'Tin', 0),
  ('leap-year', 0, '364', 0),
  ('leap-year', 1, '365', 0),
  ('leap-year', 2, '366', 1),
  ('leap-year', 3, '367', 0),
  ('ruby', 0, 'Blue', 0),
  ('ruby', 1, 'Green', 0),
  ('ruby', 2, 'Yellow', 0),
  ('ruby', 3, 'Red', 1),
  ('elephant', 0, 'Hippo', 0),
  ('elephant', 1, 'Elephant', 1),
  ('elephant', 2, 'Rhino', 0),
  ('elephant', 3, 'Giraffe', 0),
  ('puppy', 0, 'Kitten', 0),
  ('puppy', 1, 'Calf', 0),
  ('puppy', 2, 'Cub', 0),
  ('puppy', 3, 'Puppy', 1),
  ('sunrise', 0, 'North', 0),
  ('sunrise', 1, 'South', 0),
  ('sunrise', 2, 'East', 1),
  ('sunrise', 3, 'West', 0),
  ('thousand', 0, '2', 0),
  ('thousand', 1, '3', 1),
  ('thousand', 2, '4', 0),
  ('thousand', 3, '5', 0);
