INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('geography-tokyo', 'What is the capital of Japan?', 'geography', 2, 1),
  ('geography-thames', 'Which river flows through London?', 'geography', 2, 1),
  ('geography-sahara', 'Which is the largest hot desert?', 'geography', 2, 1),
  ('geography-australia', 'Which continent is also a single country?', 'geography', 2, 1),
  ('geography-everest', 'What is the highest mountain above sea level?', 'geography', 3, 1),
  ('geography-ottawa', 'What is the capital of Canada?', 'geography', 3, 1),
  ('geography-amazon', 'Which river discharges the most water?', 'geography', 3, 1),
  ('geography-gibraltar', 'Which strait separates Europe and Africa?', 'geography', 3, 1),
  ('geography-lesotho', 'Which country is entirely surrounded by South Africa?', 'geography', 4, 1),
  ('geography-baikal', 'What is the deepest lake?', 'geography', 4, 1),
  ('geography-kazakhstan', 'What is the largest landlocked country by area?', 'geography', 4, 1),
  ('geography-andes', 'What is the longest mountain range?', 'geography', 4, 1),
  ('geography-vatican', 'What is the smallest country by area?', 'geography', 5, 1),
  ('geography-atacama', 'Which desert is the driest non-polar desert?', 'geography', 5, 1),
  ('geography-angel', 'What is the tallest waterfall?', 'geography', 5, 1),
  ('geography-greenland', 'What is the largest island?', 'geography', 5, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('geography-tokyo', 0, 'Tokyo', 1),
  ('geography-tokyo', 1, 'Kyoto', 0),
  ('geography-tokyo', 2, 'Osaka', 0),
  ('geography-tokyo', 3, 'Hiroshima', 0),
  ('geography-thames', 0, 'Seine', 0),
  ('geography-thames', 1, 'Thames', 1),
  ('geography-thames', 2, 'Danube', 0),
  ('geography-thames', 3, 'Rhine', 0),
  ('geography-sahara', 0, 'Gobi', 0),
  ('geography-sahara', 1, 'Kalahari', 0),
  ('geography-sahara', 2, 'Sahara', 1),
  ('geography-sahara', 3, 'Mojave', 0),
  ('geography-australia', 0, 'Africa', 0),
  ('geography-australia', 1, 'Europe', 0),
  ('geography-australia', 2, 'Asia', 0),
  ('geography-australia', 3, 'Australia', 1),
  ('geography-everest', 0, 'Mount Everest', 1),
  ('geography-everest', 1, 'K2', 0),
  ('geography-everest', 2, 'Denali', 0),
  ('geography-everest', 3, 'Kilimanjaro', 0),
  ('geography-ottawa', 0, 'Toronto', 0),
  ('geography-ottawa', 1, 'Ottawa', 1),
  ('geography-ottawa', 2, 'Vancouver', 0),
  ('geography-ottawa', 3, 'Montreal', 0),
  ('geography-amazon', 0, 'Nile', 0),
  ('geography-amazon', 1, 'Mississippi', 0),
  ('geography-amazon', 2, 'Amazon', 1),
  ('geography-amazon', 3, 'Yangtze', 0),
  ('geography-gibraltar', 0, 'Bering Strait', 0),
  ('geography-gibraltar', 1, 'Cook Strait', 0),
  ('geography-gibraltar', 2, 'Torres Strait', 0),
  ('geography-gibraltar', 3, 'Strait of Gibraltar', 1),
  ('geography-lesotho', 0, 'Lesotho', 1),
  ('geography-lesotho', 1, 'Botswana', 0),
  ('geography-lesotho', 2, 'Namibia', 0),
  ('geography-lesotho', 3, 'Zimbabwe', 0),
  ('geography-baikal', 0, 'Lake Superior', 0),
  ('geography-baikal', 1, 'Lake Baikal', 1),
  ('geography-baikal', 2, 'Lake Victoria', 0),
  ('geography-baikal', 3, 'Lake Tanganyika', 0),
  ('geography-kazakhstan', 0, 'Mongolia', 0),
  ('geography-kazakhstan', 1, 'Chad', 0),
  ('geography-kazakhstan', 2, 'Kazakhstan', 1),
  ('geography-kazakhstan', 3, 'Bolivia', 0),
  ('geography-andes', 0, 'Rockies', 0),
  ('geography-andes', 1, 'Himalayas', 0),
  ('geography-andes', 2, 'Alps', 0),
  ('geography-andes', 3, 'Andes', 1),
  ('geography-vatican', 0, 'Vatican City', 1),
  ('geography-vatican', 1, 'Monaco', 0),
  ('geography-vatican', 2, 'San Marino', 0),
  ('geography-vatican', 3, 'Nauru', 0),
  ('geography-atacama', 0, 'Sahara', 0),
  ('geography-atacama', 1, 'Atacama', 1),
  ('geography-atacama', 2, 'Namib', 0),
  ('geography-atacama', 3, 'Gobi', 0),
  ('geography-angel', 0, 'Niagara Falls', 0),
  ('geography-angel', 1, 'Victoria Falls', 0),
  ('geography-angel', 2, 'Angel Falls', 1),
  ('geography-angel', 3, 'Iguazu Falls', 0),
  ('geography-greenland', 0, 'New Guinea', 0),
  ('geography-greenland', 1, 'Borneo', 0),
  ('geography-greenland', 2, 'Madagascar', 0),
  ('geography-greenland', 3, 'Greenland', 1);
