INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('science-photosynthesis', 'What process do plants use to make food from sunlight?', 'science', 2, 1),
  ('science-bones', 'About how many bones are in an adult human body?', 'science', 2, 1),
  ('science-gold', 'What is the chemical symbol for gold?', 'science', 2, 1),
  ('science-vacuum', 'Light travels fastest through which of these?', 'science', 2, 1),
  ('science-newton', 'Which numbered law of motion says that every action has an equal and opposite reaction?', 'science', 3, 1),
  ('science-mitochondria', 'Which part of a cell is often called the powerhouse?', 'science', 3, 1),
  ('science-ph', 'What is the pH of pure water at room temperature?', 'science', 3, 1),
  ('science-dna', 'What does DNA stand for?', 'science', 3, 1),
  ('science-absolute', 'What is absolute zero on the Celsius scale, to the nearest degree?', 'science', 4, 1),
  ('science-chromosomes', 'How many chromosomes are in a typical human body cell?', 'science', 4, 1),
  ('science-halogen', 'Which of these elements is a halogen?', 'science', 4, 1),
  ('science-hemoglobin', 'Which protein carries oxygen in red blood cells?', 'science', 4, 1),
  ('science-carbon14', 'About how long is the half-life of carbon-14?', 'science', 5, 1),
  ('science-tungsten', 'Which of these metals has the highest melting point?', 'science', 5, 1),
  ('science-light', 'About how fast does light travel in a vacuum?', 'science', 5, 1),
  ('science-ganymede', 'Which moon is the largest in the solar system?', 'science', 5, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('science-photosynthesis', 0, 'Photosynthesis', 1),
  ('science-photosynthesis', 1, 'Respiration', 0),
  ('science-photosynthesis', 2, 'Fermentation', 0),
  ('science-photosynthesis', 3, 'Digestion', 0),
  ('science-bones', 0, '106', 0),
  ('science-bones', 1, '206', 1),
  ('science-bones', 2, '306', 0),
  ('science-bones', 3, '412', 0),
  ('science-gold', 0, 'Ag', 0),
  ('science-gold', 1, 'Fe', 0),
  ('science-gold', 2, 'Au', 1),
  ('science-gold', 3, 'Pb', 0),
  ('science-vacuum', 0, 'Water', 0),
  ('science-vacuum', 1, 'Glass', 0),
  ('science-vacuum', 2, 'Diamond', 0),
  ('science-vacuum', 3, 'A vacuum', 1),
  ('science-newton', 0, 'First', 0),
  ('science-newton', 1, 'Second', 0),
  ('science-newton', 2, 'Third', 1),
  ('science-newton', 3, 'Fourth', 0),
  ('science-mitochondria', 0, 'Nucleus', 0),
  ('science-mitochondria', 1, 'Mitochondrion', 1),
  ('science-mitochondria', 2, 'Ribosome', 0),
  ('science-mitochondria', 3, 'Vacuole', 0),
  ('science-ph', 0, '0', 0),
  ('science-ph', 1, '5', 0),
  ('science-ph', 2, '7', 1),
  ('science-ph', 3, '14', 0),
  ('science-dna', 0, 'Ribonucleic acid', 0),
  ('science-dna', 1, 'Deoxyribonucleic acid', 1),
  ('science-dna', 2, 'Dinitrogen acetate', 0),
  ('science-dna', 3, 'Dinucleotide amine', 0),
  ('science-absolute', 0, '0', 0),
  ('science-absolute', 1, '-100', 0),
  ('science-absolute', 2, '-273', 1),
  ('science-absolute', 3, '-460', 0),
  ('science-chromosomes', 0, '23', 0),
  ('science-chromosomes', 1, '46', 1),
  ('science-chromosomes', 2, '48', 0),
  ('science-chromosomes', 3, '92', 0),
  ('science-halogen', 0, 'Argon', 0),
  ('science-halogen', 1, 'Neon', 0),
  ('science-halogen', 2, 'Chlorine', 1),
  ('science-halogen', 3, 'Helium', 0),
  ('science-hemoglobin', 0, 'Insulin', 0),
  ('science-hemoglobin', 1, 'Collagen', 0),
  ('science-hemoglobin', 2, 'Keratin', 0),
  ('science-hemoglobin', 3, 'Hemoglobin', 1),
  ('science-carbon14', 0, '573 years', 0),
  ('science-carbon14', 1, '5,730 years', 1),
  ('science-carbon14', 2, '57,300 years', 0),
  ('science-carbon14', 3, '573,000 years', 0),
  ('science-tungsten', 0, 'Iron', 0),
  ('science-tungsten', 1, 'Tungsten', 1),
  ('science-tungsten', 2, 'Titanium', 0),
  ('science-tungsten', 3, 'Platinum', 0),
  ('science-light', 0, '300 km/s', 0),
  ('science-light', 1, '30,000 km/s', 0),
  ('science-light', 2, '300,000 km/s', 1),
  ('science-light', 3, '3,000,000 km/s', 0),
  ('science-ganymede', 0, 'Titan', 0),
  ('science-ganymede', 1, 'Europa', 0),
  ('science-ganymede', 2, 'The Moon', 0),
  ('science-ganymede', 3, 'Ganymede', 1);
