INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('common-olympics', 'How many rings are on the Olympic flag?', 'common', 2, 1),
  ('common-chess', 'How many squares are on a chessboard?', 'common', 2, 1),
  ('common-rainbow', 'How many colors are in a traditional rainbow?', 'common', 2, 1),
  ('common-deck', 'How many cards are in a standard deck, not counting jokers?', 'common', 2, 1),
  ('common-mona-lisa', 'Who painted the Mona Lisa?', 'common', 3, 1),
  ('common-yen', 'What is the currency of Japan?', 'common', 3, 1),
  ('common-shakespeare', 'Who wrote Romeo and Juliet?', 'common', 3, 1),
  ('common-stars', 'How many stars are on the flag of the United States?', 'common', 3, 1),
  ('common-braille', 'How many dots are in a full Braille cell?', 'common', 4, 1),
  ('common-roman', 'What number does the Roman numeral XL stand for?', 'common', 4, 1),
  ('common-greenwich', 'The prime meridian passes through which of these places?', 'common', 4, 1),
  ('common-athens', 'Which city hosted the first modern Olympic Games?', 'common', 4, 1),
  ('common-googol', 'A googol is 10 raised to what power?', 'common', 5, 1),
  ('common-pangram', 'What do you call a sentence that uses every letter of the alphabet?', 'common', 5, 1),
  ('common-esperanto', 'Who created the language Esperanto?', 'common', 5, 1),
  ('common-scrabble', 'In English Scrabble, how many points is the letter Q worth?', 'common', 5, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('common-olympics', 0, '5', 1),
  ('common-olympics', 1, '6', 0),
  ('common-olympics', 2, '7', 0),
  ('common-olympics', 3, '8', 0),
  ('common-chess', 0, '32', 0),
  ('common-chess', 1, '64', 1),
  ('common-chess', 2, '81', 0),
  ('common-chess', 3, '100', 0),
  ('common-rainbow', 0, '5', 0),
  ('common-rainbow', 1, '6', 0),
  ('common-rainbow', 2, '7', 1),
  ('common-rainbow', 3, '8', 0),
  ('common-deck', 0, '48', 0),
  ('common-deck', 1, '50', 0),
  ('common-deck', 2, '54', 0),
  ('common-deck', 3, '52', 1),
  ('common-mona-lisa', 0, 'Leonardo da Vinci', 1),
  ('common-mona-lisa', 1, 'Michelangelo', 0),
  ('common-mona-lisa', 2, 'Raphael', 0),
  ('common-mona-lisa', 3, 'Donatello', 0),
  ('common-yen', 0, 'Won', 0),
  ('common-yen', 1, 'Yen', 1),
  ('common-yen', 2, 'Yuan', 0),
  ('common-yen', 3, 'Ringgit', 0),
  ('common-shakespeare', 0, 'Charles Dickens', 0),
  ('common-shakespeare', 1, 'Geoffrey Chaucer', 0),
  ('common-shakespeare', 2, 'William Shakespeare', 1),
  ('common-shakespeare', 3, 'Oscar Wilde', 0),
  ('common-stars', 0, '48', 0),
  ('common-stars', 1, '49', 0),
  ('common-stars', 2, '50', 1),
  ('common-stars', 3, '52', 0),
  ('common-braille', 0, '6', 1),
  ('common-braille', 1, '8', 0),
  ('common-braille', 2, '9', 0),
  ('common-braille', 3, '10', 0),
  ('common-roman', 0, '14', 0),
  ('common-roman', 1, '40', 1),
  ('common-roman', 2, '60', 0),
  ('common-roman', 3, '90', 0),
  ('common-greenwich', 0, 'Paris', 0),
  ('common-greenwich', 1, 'Cairo', 0),
  ('common-greenwich', 2, 'Greenwich', 1),
  ('common-greenwich', 3, 'Madrid', 0),
  ('common-athens', 0, 'Paris', 0),
  ('common-athens', 1, 'London', 0),
  ('common-athens', 2, 'Rome', 0),
  ('common-athens', 3, 'Athens', 1),
  ('common-googol', 0, '100', 1),
  ('common-googol', 1, '1,000', 0),
  ('common-googol', 2, '10,000', 0),
  ('common-googol', 3, '1,000,000', 0),
  ('common-pangram', 0, 'Palindrome', 0),
  ('common-pangram', 1, 'Pangram', 1),
  ('common-pangram', 2, 'Anagram', 0),
  ('common-pangram', 3, 'Acronym', 0),
  ('common-esperanto', 0, 'J. R. R. Tolkien', 0),
  ('common-esperanto', 1, 'Noam Chomsky', 0),
  ('common-esperanto', 2, 'L. L. Zamenhof', 1),
  ('common-esperanto', 3, 'Dr. Seuss', 0),
  ('common-scrabble', 0, '5', 0),
  ('common-scrabble', 1, '8', 0),
  ('common-scrabble', 2, '12', 0),
  ('common-scrabble', 3, '10', 1);
