INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('movies-frozen', 'Which movie features the song Let It Go?', 'movies', 1, 1),
  ('movies-toto', 'What is the name of Dorothy''s dog in The Wizard of Oz?', 'movies', 1, 1),
  ('movies-nemo', 'What kind of fish is Nemo in Finding Nemo?', 'movies', 1, 1),
  ('movies-shrek', 'What kind of creature is Shrek?', 'movies', 1, 1),
  ('movies-hogwarts', 'Which school does Harry Potter attend?', 'movies', 2, 1),
  ('movies-gotham', 'Which city does Batman protect?', 'movies', 2, 1),
  ('movies-simba', 'What kind of animal is Simba in The Lion King?', 'movies', 2, 1),
  ('movies-titanic', 'Who directed Titanic?', 'movies', 2, 1),
  ('movies-godfather', 'Which film popularized the line about an offer he cannot refuse?', 'movies', 3, 1),
  ('movies-vader', 'Who is Luke Skywalker''s father?', 'movies', 3, 1),
  ('movies-inception', 'Which Christopher Nolan film is about entering dreams?', 'movies', 3, 1),
  ('movies-forrest', 'Which film includes the line about life and a box of chocolates?', 'movies', 3, 1),
  ('movies-spirited', 'Which Studio Ghibli film follows Chihiro in a spirit bathhouse?', 'movies', 4, 1),
  ('movies-casablanca', 'Which film includes the line ''Here''s looking at you, kid''?', 'movies', 4, 1),
  ('movies-psycho', 'Which Alfred Hitchcock film is known for its shower scene?', 'movies', 4, 1),
  ('movies-parasite', 'Which film was the first non-English-language winner of the Oscar for Best Picture?', 'movies', 4, 1),
  ('movies-kane', 'Rosebud is a famous last word from which film?', 'movies', 5, 1),
  ('movies-bicycle', 'Which Italian film follows a man whose bicycle is stolen?', 'movies', 5, 1),
  ('movies-samurai', 'Who directed Seven Samurai?', 'movies', 5, 1),
  ('movies-metropolis', 'Who directed the 1927 science-fiction film Metropolis?', 'movies', 5, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('movies-frozen', 0, 'Frozen', 1),
  ('movies-frozen', 1, 'Moana', 0),
  ('movies-frozen', 2, 'Encanto', 0),
  ('movies-frozen', 3, 'Tangled', 0),
  ('movies-toto', 0, 'Lassie', 0),
  ('movies-toto', 1, 'Toto', 1),
  ('movies-toto', 2, 'Beethoven', 0),
  ('movies-toto', 3, 'Scooby', 0),
  ('movies-nemo', 0, 'Shark', 0),
  ('movies-nemo', 1, 'Whale', 0),
  ('movies-nemo', 2, 'Clownfish', 1),
  ('movies-nemo', 3, 'Octopus', 0),
  ('movies-shrek', 0, 'Troll', 0),
  ('movies-shrek', 1, 'Giant', 0),
  ('movies-shrek', 2, 'Elf', 0),
  ('movies-shrek', 3, 'Ogre', 1),
  ('movies-hogwarts', 0, 'Hogwarts', 1),
  ('movies-hogwarts', 1, 'Beauxbatons', 0),
  ('movies-hogwarts', 2, 'Durmstrang', 0),
  ('movies-hogwarts', 3, 'Ilvermorny', 0),
  ('movies-gotham', 0, 'Metropolis', 0),
  ('movies-gotham', 1, 'Gotham', 1),
  ('movies-gotham', 2, 'Star City', 0),
  ('movies-gotham', 3, 'Central City', 0),
  ('movies-simba', 0, 'Tiger', 0),
  ('movies-simba', 1, 'Wolf', 0),
  ('movies-simba', 2, 'Lion', 1),
  ('movies-simba', 3, 'Bear', 0),
  ('movies-titanic', 0, 'Steven Spielberg', 0),
  ('movies-titanic', 1, 'Christopher Nolan', 0),
  ('movies-titanic', 2, 'Ridley Scott', 0),
  ('movies-titanic', 3, 'James Cameron', 1),
  ('movies-godfather', 0, 'The Godfather', 1),
  ('movies-godfather', 1, 'Scarface', 0),
  ('movies-godfather', 2, 'Goodfellas', 0),
  ('movies-godfather', 3, 'Casino', 0),
  ('movies-vader', 0, 'Obi-Wan Kenobi', 0),
  ('movies-vader', 1, 'Darth Vader', 1),
  ('movies-vader', 2, 'Yoda', 0),
  ('movies-vader', 3, 'Han Solo', 0),
  ('movies-inception', 0, 'Interstellar', 0),
  ('movies-inception', 1, 'Tenet', 0),
  ('movies-inception', 2, 'Inception', 1),
  ('movies-inception', 3, 'The Prestige', 0),
  ('movies-forrest', 0, 'Cast Away', 0),
  ('movies-forrest', 1, 'Big', 0),
  ('movies-forrest', 2, 'Philadelphia', 0),
  ('movies-forrest', 3, 'Forrest Gump', 1),
  ('movies-spirited', 0, 'Spirited Away', 1),
  ('movies-spirited', 1, 'My Neighbor Totoro', 0),
  ('movies-spirited', 2, 'Howl''s Moving Castle', 0),
  ('movies-spirited', 3, 'Princess Mononoke', 0),
  ('movies-casablanca', 0, 'Gone with the Wind', 0),
  ('movies-casablanca', 1, 'Casablanca', 1),
  ('movies-casablanca', 2, 'Citizen Kane', 0),
  ('movies-casablanca', 3, 'Rebecca', 0),
  ('movies-psycho', 0, 'Vertigo', 0),
  ('movies-psycho', 1, 'Rear Window', 0),
  ('movies-psycho', 2, 'Psycho', 1),
  ('movies-psycho', 3, 'The Birds', 0),
  ('movies-parasite', 0, 'Roma', 0),
  ('movies-parasite', 1, 'Amour', 0),
  ('movies-parasite', 2, 'Crouching Tiger, Hidden Dragon', 0),
  ('movies-parasite', 3, 'Parasite', 1),
  ('movies-kane', 0, 'Citizen Kane', 1),
  ('movies-kane', 1, 'The Maltese Falcon', 0),
  ('movies-kane', 2, 'Vertigo', 0),
  ('movies-kane', 3, 'Sunset Boulevard', 0),
  ('movies-bicycle', 0, 'Rome, Open City', 0),
  ('movies-bicycle', 1, 'Bicycle Thieves', 1),
  ('movies-bicycle', 2, 'La Strada', 0),
  ('movies-bicycle', 3, '8 1/2', 0),
  ('movies-samurai', 0, 'Yasujiro Ozu', 0),
  ('movies-samurai', 1, 'Kenji Mizoguchi', 0),
  ('movies-samurai', 2, 'Akira Kurosawa', 1),
  ('movies-samurai', 3, 'Masaki Kobayashi', 0),
  ('movies-metropolis', 0, 'F. W. Murnau', 0),
  ('movies-metropolis', 1, 'Robert Wiene', 0),
  ('movies-metropolis', 2, 'Sergei Eisenstein', 0),
  ('movies-metropolis', 3, 'Fritz Lang', 1);
