INSERT INTO questions (id, prompt, category, difficulty, active) VALUES
  ('history-moon', 'In what year did astronauts first walk on the Moon?', 'history', 1, 1),
  ('history-columbus', 'In what year did Christopher Columbus first reach the Americas?', 'history', 1, 1),
  ('history-declaration', 'In what year was the United States Declaration of Independence adopted?', 'history', 1, 1),
  ('history-colosseum', 'Which amphitheater did ancient Rome use for gladiator games?', 'history', 1, 1),
  ('history-ww2', 'In what year did World War II end?', 'history', 2, 1),
  ('history-napoleon', 'Napoleon Bonaparte was emperor of which country?', 'history', 2, 1),
  ('history-washington', 'Who was the first president of the United States?', 'history', 2, 1),
  ('history-berlin', 'In what year did the Berlin Wall fall?', 'history', 2, 1),
  ('history-magna', 'In what year was Magna Carta sealed?', 'history', 3, 1),
  ('history-french', 'In what year did the French Revolution begin?', 'history', 3, 1),
  ('history-constantinople', 'In what year did the Ottomans capture Constantinople?', 'history', 3, 1),
  ('history-renaissance', 'The Renaissance began in which country?', 'history', 3, 1),
  ('history-rosetta', 'The Rosetta Stone was the key to reading which writing system?', 'history', 4, 1),
  ('history-hastings', 'In what year was the Battle of Hastings?', 'history', 4, 1),
  ('history-mansa', 'Mansa Musa ruled which empire?', 'history', 4, 1),
  ('history-westphalia', 'The 1648 Peace of Westphalia ended which war?', 'history', 4, 1),
  ('history-qin', 'Who was the first emperor of a unified China?', 'history', 5, 1),
  ('history-constantine', 'Which Roman emperor issued the Edict of Milan in 313?', 'history', 5, 1),
  ('history-hammurabi', 'Which ancient Babylonian text is a famous law code?', 'history', 5, 1),
  ('history-tordesillas', 'Which 1494 treaty split newly claimed lands between Spain and Portugal?', 'history', 5, 1);

INSERT INTO choices (question_id, position, text, is_correct) VALUES
  ('history-moon', 0, '1969', 1),
  ('history-moon', 1, '1957', 0),
  ('history-moon', 2, '1975', 0),
  ('history-moon', 3, '1981', 0),
  ('history-columbus', 0, '1066', 0),
  ('history-columbus', 1, '1492', 1),
  ('history-columbus', 2, '1776', 0),
  ('history-columbus', 3, '1812', 0),
  ('history-declaration', 0, '1492', 0),
  ('history-declaration', 1, '1620', 0),
  ('history-declaration', 2, '1776', 1),
  ('history-declaration', 3, '1865', 0),
  ('history-colosseum', 0, 'The Forum', 0),
  ('history-colosseum', 1, 'The Pantheon', 0),
  ('history-colosseum', 2, 'The Circus Maximus', 0),
  ('history-colosseum', 3, 'The Colosseum', 1),
  ('history-ww2', 0, '1945', 1),
  ('history-ww2', 1, '1918', 0),
  ('history-ww2', 2, '1939', 0),
  ('history-ww2', 3, '1953', 0),
  ('history-napoleon', 0, 'Spain', 0),
  ('history-napoleon', 1, 'France', 1),
  ('history-napoleon', 2, 'Austria', 0),
  ('history-napoleon', 3, 'Russia', 0),
  ('history-washington', 0, 'John Adams', 0),
  ('history-washington', 1, 'Thomas Jefferson', 0),
  ('history-washington', 2, 'George Washington', 1),
  ('history-washington', 3, 'James Madison', 0),
  ('history-berlin', 0, '1961', 0),
  ('history-berlin', 1, '1979', 0),
  ('history-berlin', 2, '1985', 0),
  ('history-berlin', 3, '1989', 1),
  ('history-magna', 0, '1215', 1),
  ('history-magna', 1, '1066', 0),
  ('history-magna', 2, '1415', 0),
  ('history-magna', 3, '1588', 0),
  ('history-french', 0, '1688', 0),
  ('history-french', 1, '1789', 1),
  ('history-french', 2, '1815', 0),
  ('history-french', 3, '1848', 0),
  ('history-constantinople', 0, '1204', 0),
  ('history-constantinople', 1, '1389', 0),
  ('history-constantinople', 2, '1453', 1),
  ('history-constantinople', 3, '1529', 0),
  ('history-renaissance', 0, 'France', 0),
  ('history-renaissance', 1, 'England', 0),
  ('history-renaissance', 2, 'Spain', 0),
  ('history-renaissance', 3, 'Italy', 1),
  ('history-rosetta', 0, 'Egyptian hieroglyphs', 1),
  ('history-rosetta', 1, 'Cuneiform', 0),
  ('history-rosetta', 2, 'Linear B', 0),
  ('history-rosetta', 3, 'Sanskrit', 0),
  ('history-hastings', 0, '1014', 0),
  ('history-hastings', 1, '1066', 1),
  ('history-hastings', 2, '1415', 0),
  ('history-hastings', 3, '1485', 0),
  ('history-mansa', 0, 'Songhai', 0),
  ('history-mansa', 1, 'Ghana', 0),
  ('history-mansa', 2, 'Mali', 1),
  ('history-mansa', 3, 'Aksum', 0),
  ('history-westphalia', 0, 'Hundred Years War', 0),
  ('history-westphalia', 1, 'Wars of the Roses', 0),
  ('history-westphalia', 2, 'Napoleonic Wars', 0),
  ('history-westphalia', 3, 'Thirty Years War', 1),
  ('history-qin', 0, 'Qin Shi Huang', 1),
  ('history-qin', 1, 'Kublai Khan', 0),
  ('history-qin', 2, 'Wu Zetian', 0),
  ('history-qin', 3, 'Sun Yat-sen', 0),
  ('history-constantine', 0, 'Nero', 0),
  ('history-constantine', 1, 'Constantine', 1),
  ('history-constantine', 2, 'Augustus', 0),
  ('history-constantine', 3, 'Diocletian', 0),
  ('history-hammurabi', 0, 'The Epic of Gilgamesh', 0),
  ('history-hammurabi', 1, 'The Book of the Dead', 0),
  ('history-hammurabi', 2, 'The Code of Hammurabi', 1),
  ('history-hammurabi', 3, 'The Rigveda', 0),
  ('history-tordesillas', 0, 'Treaty of Versailles', 0),
  ('history-tordesillas', 1, 'Treaty of Utrecht', 0),
  ('history-tordesillas', 2, 'Treaty of Paris', 0),
  ('history-tordesillas', 3, 'Treaty of Tordesillas', 1);
