// Generated by scripts/catalog-migrations.mjs. Do not edit.
import type { CatalogMigration } from "../server/catalog.ts"
import sql_0001_questions_sql from "../migrations/0001_questions.sql"
import sql_0002_seed_sql from "../migrations/0002_seed.sql"
import sql_0003_question_stats_sql from "../migrations/0003_question_stats.sql"
import sql_0004_categories_sql from "../migrations/0004_categories.sql"
import sql_0005_geography_sql from "../migrations/0005_geography.sql"
import sql_0006_science_sql from "../migrations/0006_science.sql"
import sql_0007_common_sql from "../migrations/0007_common.sql"
import sql_0008_movies_sql from "../migrations/0008_movies.sql"
import sql_0009_history_sql from "../migrations/0009_history.sql"

export const MIGRATIONS: CatalogMigration[] = [
  { name: "0001_questions.sql", sql: sql_0001_questions_sql },
  { name: "0002_seed.sql", sql: sql_0002_seed_sql },
  { name: "0003_question_stats.sql", sql: sql_0003_question_stats_sql },
  { name: "0004_categories.sql", sql: sql_0004_categories_sql },
  { name: "0005_geography.sql", sql: sql_0005_geography_sql },
  { name: "0006_science.sql", sql: sql_0006_science_sql },
  { name: "0007_common.sql", sql: sql_0007_common_sql },
  { name: "0008_movies.sql", sql: sql_0008_movies_sql },
  { name: "0009_history.sql", sql: sql_0009_history_sql },
]
